version: '3'


services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7001:3000"
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7002:3000"
  server3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7003:3000"
  server4:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7004:3000"
  server5:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7005:3000"